Repository Team-Clip-Clibi/Backend, pull requests merged in 2025-05, with the labels that each got.

#125 feat/onething-matching
  boot/api/src/main/java/com/clip/api/docs/matching/OneThingMatchingDocs.java
  boot/api/src/main/java/com/clip/api/matching/controller/UserOneThingMatchingController.java
  boot/api/src/main/java/com/clip/api/matching/controller/dto/OneThingOrderDto.java
  boot/api/src/main/java/com/clip/api/matching/service/OneThingMatchingOrderService.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/OneThingMatchingOrderServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/UserMatchingServiceTest.java
  boot/api/src/test/java/data/coredata/com/clip/auth/entity/repository/TokenRepositoryTest.java
  boot/api/src/test/java/data/coredata/com/clip/order/entity/repository/OneThingOrderRepositoryTest.java
  boot/office/src/main/java/com/clip/office/matching/controller/dto/CreateOneThingMatchingDto.java
  boot/office/src/main/java/com/clip/office/matching/controller/dto/OneThingMatchingDto.java
  boot/office/src/main/java/com/clip/office/matching/controller/dto/UpdateOneThingMatchingDto.java
  boot/office/src/main/java/com/clip/office/matching/service/OneThingMatchingService.java
  data/core-data/src/main/java/com/clip/auth/repository/TokenRepository.java
  data/core-data/src/main/java/com/clip/auth/service/TokenService.java
  data/core-data/src/main/java/com/clip/matching/entity/OneThingBudgetRange.java
  data/core-data/src/main/java/com/clip/matching/entity/OneThingMatching.java
  data/core-data/src/main/java/com/clip/matching/entity/OneThingTimeSlot.java
  data/core-data/src/main/java/com/clip/matching/entity/UserOneThingMatching.java
  data/core-data/src/main/java/com/clip/matching/service/UserOneThingMatchingService.java
  data/core-data/src/main/java/com/clip/order/entity/OneThingOrder.java
  data/core-data/src/main/java/com/clip/order/entity/RandomOrder.java
  data/core-data/src/main/java/com/clip/order/entity/RandomOrderStatus.java
  data/core-data/src/main/java/com/clip/order/service/OneThingOrderService.java
  data/core-data/src/main/java/com/clip/toss/entity/TossPayment.java
Labels: feature, 정우

#122 feat : 푸시 알림 기능 구현
  boot/api/build.gradle
  boot/api/src/main/java/com/clip/ApiApplication.java
  boot/api/src/main/java/com/clip/api/docs/display/DisplayInfoDocs.java
  boot/api/src/main/java/com/clip/batch/config/ShedLockConfig.java
  boot/api/src/main/java/com/clip/batch/notification/OneThingMatchingInfoNotificationBatchConfig.java
  boot/api/src/main/java/com/clip/batch/notification/OneThingMatchingProgressNotificationBatchConfig.java
  boot/api/src/main/java/com/clip/batch/notification/RandomMatchingInfoNotificationBatchConfig.java
  boot/api/src/main/java/com/clip/batch/notification/RandomMatchingProgressNotificationBatchConfig.java
  boot/api/src/main/java/com/clip/batch/notification/event/FcmSendFailedEventListener.java
  boot/api/src/main/java/com/clip/batch/notification/service/MatchingNotificationService.java
  boot/api/src/main/java/com/clip/batch/notification/service/MatchingProgressNotificationService.java
  boot/api/src/main/resources/application.yml
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/OneThingMatchingOrderServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/UserMatchingReviewServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/UserMatchingServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/report/service/UserReportServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTokenTest.java
  boot/api/src/test/java/data/coredata/com/clip/notification/service/NotificationServiceTest.java
  boot/api/src/test/resources/application.yml
  boot/office/src/test/java/com/clip/office/matching/service/RandomMatchingServiceTest.java
  boot/office/src/test/java/com/clip/office/notice/service/BannerServiceTest.java
  boot/office/src/test/java/com/clip/office/notice/service/NoticeServiceTest.java
  data/core-data/src/main/java/com/clip/matching/entity/RandomMatching.java
  data/core-data/src/main/java/com/clip/matching/entity/UserOneThingMatching.java
  data/core-data/src/main/java/com/clip/notification/entity/Notification.java
  data/core-data/src/main/java/com/clip/notification/entity/SendStatus.java
  data/core-data/src/main/java/com/clip/notification/repository/NotificationRepository.java
  data/core-data/src/main/java/com/clip/notification/service/NotificationService.java
  data/core-data/src/main/java/com/clip/user/repository/JobRepository.java
  data/core-data/src/main/java/com/clip/user/repository/UserJobRepository.java
  infra/build.gradle
  infra/src/main/java/com/clip/infra/aws/s3/S3FCMService.java
  infra/src/main/java/com/clip/infra/fcm/config/FcmConfig.java
  infra/src/main/java/com/clip/infra/fcm/event/FcmNotificationEvent.java
  infra/src/main/java/com/clip/infra/fcm/event/FcmNotificationEventListener.java
  infra/src/main/java/com/clip/infra/fcm/event/FcmSendFailedEvent.java
  infra/src/main/java/com/clip/infra/fcm/exception/FcmServerException.java
  infra/src/main/java/com/clip/infra/fcm/service/FCMMsgGenerator.java
  infra/src/main/java/com/clip/infra/fcm/service/FCMMsgSender.java
  infra/src/main/java/com/clip/infra/fcm/service/MessageParams.java
  infra/src/main/java/com/clip/infra/fcm/service/MessageTemplateType.java
  infra/src/main/java/com/clip/infra/fcm/service/SendFCMService.java
  infra/src/main/resources/application-infra.yml
Labels: feature, 세은

#135 refactor/SCRUM-71
  boot/api/src/main/java/com/clip/api/matching/service/UserMatchingService.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/main/java/com/clip/global/exception/ValidExceptionHandler.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/UserMatchingServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  data/core-data/src/main/java/com/clip/global/exception/NoContentAvailableException.java
  data/core-data/src/main/java/com/clip/global/exception/ResourceAlreadyExistException.java
  data/core-data/src/main/java/com/clip/global/exception/ResourceNotFoundException.java
  data/core-data/src/main/java/com/clip/matching/exception/MatchingNotFoundException.java
  data/core-data/src/main/java/com/clip/matching/exception/NotExistMatchingException.java
  data/core-data/src/main/java/com/clip/matching/service/MatchingService.java
  data/core-data/src/main/java/com/clip/notification/exception/NotExistNotificationException.java
  data/core-data/src/main/java/com/clip/notification/service/NotificationService.java
  data/core-data/src/main/java/com/clip/order/exception/OrderNotFoundException.java
  data/core-data/src/main/java/com/clip/order/service/OneThingOrderService.java
  data/core-data/src/main/java/com/clip/order/service/RandomOrderService.java
  data/core-data/src/main/java/com/clip/user/exception/NicknameAlreadyExistsException.java
  data/core-data/src/main/java/com/clip/user/exception/PhoneNumberAlreadyExistsException.java
  data/core-data/src/main/java/com/clip/user/exception/UserNotFoundException.java
  data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: 정우, refactor

#139 정책에 따른 로직 수정 및 매칭 중복 여부 체크 API 구현
  boot/api/src/main/java/com/clip/api/docs/matching/RandomMatchingDocs.java
  boot/api/src/main/java/com/clip/api/matching/controller/UserRandomMatchingController.java
  boot/api/src/main/java/com/clip/api/matching/controller/dto/RandomMatchingDuplicateCheckDto.java
  boot/api/src/main/java/com/clip/api/matching/service/RandomMatchingOrderService.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/RandomMatchingOrderServiceTest.java
  data/core-data/src/main/java/com/clip/matching/repository/RandomMatchingCapacityRepository.java
  data/core-data/src/main/java/com/clip/matching/repository/UserRandomMatchingRepository.java
  data/core-data/src/main/java/com/clip/matching/service/MatchingService.java
  data/core-data/src/main/java/com/clip/matching/service/UserRandomMatchingService.java
  data/core-data/src/main/java/com/clip/notification/entity/Notification.java
Labels: feature, 세은

#141 refactor : 내 모임 리스트 조회 API에 후기 작성 여부 필드 추가
  boot/api/src/main/java/com/clip/api/docs/matching/UserMatchingDocs.java
  boot/api/src/main/java/com/clip/api/matching/controller/dto/MatchingDto.java
  data/core-data/src/main/java/com/clip/matching/repository/UserMatchingRepository.java
  data/core-data/src/main/java/com/clip/matching/repository/projection/MatchingProjectionDto.java
Labels: refactor, 세은

#142 fix/SCRUM-78
  boot/api/src/main/java/com/clip/api/matching/service/OneThingMatchingOrderService.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/OneThingMatchingOrderServiceTest.java
  data/core-data/src/main/java/com/clip/matching/entity/UserOneThingMatching.java
Labels: 정우, fix
