Repository Team-Clip-Clibi/Backend, pull requests merged in 2025-06, with the labels that each got.

#150 FeignConfig errorDecoder 추가 및 로깅 코드 추가
  boot/api/src/main/java/com/clip/api/payment/feign/dto/PaymentObject.java
  boot/api/src/main/java/com/clip/api/payment/service/PaymentServiceFacade.java
  boot/api/src/main/java/com/clip/global/config/feign/FeignConfig.java
Labels: feature

#151 refactor : 랜덤 매칭 중복 신청 쿼리 수정 및 결제 이후 로직 추가
  boot/api/src/main/java/com/clip/api/matching/service/RandomMatchingOrderService.java
  boot/api/src/main/java/com/clip/api/payment/service/PaymentServiceFacade.java
  boot/api/src/main/java/com/clip/api/payment/service/UserPaymentService.java
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/RandomMatchingOrderServiceTest.java
  data/core-data/src/main/java/com/clip/global/exception/ResourceNotFoundException.java
  data/core-data/src/main/java/com/clip/matching/entity/UserRandomMatching.java
  data/core-data/src/main/java/com/clip/matching/repository/UserMatchingRepository.java
  data/core-data/src/main/java/com/clip/matching/repository/UserRandomMatchingRepository.java
  data/core-data/src/main/java/com/clip/matching/service/UserRandomMatchingService.java
Labels: refactor, 세은

#159 feat/SCRUM-103
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountV2Docs.java
  boot/api/src/main/java/com/clip/api/user/controller/UserAccountV2Controller.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/main/java/com/clip/global/config/jwt/TokenProvider.java
  boot/api/src/main/resources/application.yml
Labels: feature, 정우

#160 build: docker-compose.yml 추가 keyCloak, office api module
  boot/office/docker-compose.yml
Labels: 정우
