Repository Team-Clip-Clibi/Backend, pull requests merged in 2025-04, with the labels that each got.

#63 refactor/login-attempt-limit
  boot/office/src/main/java/com/clip/global/config/SecurityConfig.java
  boot/office/src/main/java/com/clip/global/config/WebConfig.java
  boot/office/src/main/java/com/clip/global/security/CustomAuthenticationFailureHandler.java
  boot/office/src/main/java/com/clip/global/security/CustomAuthenticationSuccessHandler.java
  boot/office/src/main/java/com/clip/global/security/LoginAttemptFilter.java
  boot/office/src/main/java/com/clip/global/security/util/LoginAttemptManager.java
  boot/office/src/main/java/com/clip/office/admin/service/AdminUserDetailsService.java
  boot/office/src/main/resources/application.yml
  data/office-data/src/main/java/com/clip/admin/service/AdminUserService.java
Labels: 정우, refactor

#71 분산락
  boot/office/build.gradle
  boot/office/src/main/java/com/clip/global/config/RedissonConfig.java
  boot/office/src/main/java/com/clip/global/security/CustomAuthenticationFailureHandler.java
  boot/office/src/main/java/com/clip/global/security/util/DistributeLockService.java
  boot/office/src/test/java/com/clip/office/admin/controller/AdminControllerTest.java
  boot/office/src/test/resources/application.yml
Labels: feature, 정우

#73 feat/access-token-reissue
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  boot/api/src/main/java/com/clip/api/health/HealthCheckController.java
  boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/main/java/com/clip/api/user/service/exception/TokenValidationException.java
  boot/api/src/main/java/com/clip/global/config/jwt/TokenProvider.java
  boot/api/src/main/java/com/clip/global/exception/ValidExceptionHandler.java
  boot/api/src/main/resources/application.yml
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/global/config/jwt/TokenProviderTest.java
  data/core-data/src/main/java/com/clip/auth/exception/TokenNotFoundException.java
  data/core-data/src/main/java/com/clip/auth/repository/TokenRepository.java
  data/core-data/src/main/java/com/clip/auth/service/TokenService.java
Labels: feature, 정우

#75 feat/access-token-reissue
  boot/api/src/main/java/com/clip/global/config/jwt/JwtAuthenticationFilter.java
Labels: 정우

#85 탈퇴 기능 구현
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  data/core-data/src/main/java/com/clip/user/repository/TermsAcceptanceRepository.java
  data/core-data/src/main/java/com/clip/user/repository/UserRepository.java
  data/core-data/src/main/java/com/clip/user/service/TermsAcceptanceService.java
  data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: feature, 정우

#91 feat/notification-api
  boot/api/src/main/java/com/clip/api/docs/notification/UserNotificationDocs.java
  boot/api/src/main/java/com/clip/api/notification/controller/UserNotificationController.java
  boot/api/src/main/java/com/clip/api/notification/controller/dto/NotificationDto.java
  boot/api/src/main/java/com/clip/api/notification/mapper/NotificationMapper.java
  boot/api/src/main/java/com/clip/api/notification/service/UserNotificationService.java
  boot/api/src/main/java/com/clip/global/config/jwt/JwtAuthenticationFilter.java
  boot/api/src/main/java/com/clip/global/exception/ValidExceptionHandler.java
  boot/api/src/test/java/data/coredata/com/clip/notification/service/NotificationServiceTest.java
  boot/api/src/test/java/data/coredata/com/clip/user/repository/UserRepositoryTest.java
  data/core-data/src/main/java/com/clip/notification/entity/Notification.java
  data/core-data/src/main/java/com/clip/notification/entity/NotificationType.java
  data/core-data/src/main/java/com/clip/notification/exception/NotExistNotificationException.java
  data/core-data/src/main/java/com/clip/notification/repository/NotificationRepository.java
  data/core-data/src/main/java/com/clip/notification/service/NotificationService.java
Labels: feature, 정우

#102 랜덤모임 수정, 삭제 + 생성 모달 창
  boot/office/src/main/java/com/clip/office/matching/controller/RandomMatchingController.java
  boot/office/src/main/java/com/clip/office/matching/controller/dto/UpdateRandomMatchingDto.java
  boot/office/src/main/java/com/clip/office/matching/service/RandomMatchingService.java
  boot/office/src/main/resources/static/js/matching.js
  boot/office/src/main/resources/templates/fragments/content.html
  boot/office/src/main/resources/templates/fragments/sidebar.html
  boot/office/src/test/java/com/clip/office/matching/service/RandomMatchingServiceTest.java
  data/core-data/src/main/java/com/clip/matching/entity/RandomMatching.java
  data/core-data/src/main/java/com/clip/matching/repository/RandomMatchingRepository.java
  data/core-data/src/main/java/com/clip/matching/service/RandomMatchingDataService.java
Labels: feature, 승범

#108 News -> Notice 로 통합 enum으로 관리
  boot/office/src/main/java/com/clip/office/notice/controller/NewsController.java
  boot/office/src/main/java/com/clip/office/notice/controller/NoticeController.java
  boot/office/src/main/java/com/clip/office/notice/controller/dto/CreateNoticeDto.java
  boot/office/src/main/java/com/clip/office/notice/controller/dto/UpdateNoticeDto.java
  boot/office/src/main/java/com/clip/office/notice/service/NewsService.java
  boot/office/src/main/java/com/clip/office/notice/service/NoticeService.java
  boot/office/src/test/java/com/clip/office/notice/service/NoticeServiceTest.java
  data/office-data/src/main/java/com/clip/notice/entity/News.java
  data/office-data/src/main/java/com/clip/notice/entity/Notice.java
  data/office-data/src/main/java/com/clip/notice/entity/NoticeType.java
  data/office-data/src/main/java/com/clip/notice/exception/NewsNotFoundException.java
  data/office-data/src/main/java/com/clip/notice/exception/NoticeNotFoundException.java
  data/office-data/src/main/java/com/clip/notice/repository/NoticeRepository.java
  data/office-data/src/main/java/com/clip/notice/service/NewsDataService.java
  data/office-data/src/main/java/com/clip/notice/service/NoticeDataService.java
Labels: 승범, refactor

#112 홈화면 배너 조회 기능 구현
  boot/api/build.gradle
  boot/api/src/main/java/com/clip/api/display/controller/DisplayInfoController.java
  boot/api/src/main/java/com/clip/api/display/controller/dto/BannerInfoDto.java
  boot/api/src/main/java/com/clip/api/display/service/DisplayInfoService.java
  boot/api/src/main/java/com/clip/api/docs/display/DisplayInfoDocs.java
  boot/api/src/main/resources/application.yml
  boot/api/src/test/java/boot/api/com/clip/api/matching/service/UserMatchingReviewServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/report/service/UserReportServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTokenTest.java
  boot/api/src/test/java/data/coredata/com/clip/notification/service/NotificationServiceTest.java
  boot/office/build.gradle
  boot/office/src/main/java/com/clip/global/service/S3Service.java
  boot/office/src/main/java/com/clip/office/notice/service/BannerService.java
  boot/office/src/main/resources/application.yml
  boot/office/src/test/java/com/clip/office/matching/service/RandomMatchingServiceTest.java
  boot/office/src/test/java/com/clip/office/notice/service/BannerServiceTest.java
  boot/office/src/test/java/com/clip/office/notice/service/NoticeServiceTest.java
  data/office-data/src/main/java/com/clip/notice/repository/BannerRepository.java
  data/office-data/src/main/java/com/clip/notice/service/BannerDataService.java
  infra/build.gradle
  infra/src/main/java/com/clip/infra/aws/s3/S3Config.java
  infra/src/main/java/com/clip/infra/aws/s3/S3ImgService.java
  infra/src/main/resources/application-infra.yml
Labels: feature, 세은
