Repository Team-Clip-Clibi/Backend, pull requests merged in 2025-03, with the labels that each got.

#2 feat/signup
  onething/boot/api/build.gradle
  onething/boot/api/src/main/java/com/clip/ApiApplication.java
  onething/boot/api/src/main/java/com/clip/api/a
  onething/boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/LoginDto.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/SignupDto.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateNameDto.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateNicknameDto.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/UpdatePhoneNumberDto.java
  onething/boot/api/src/main/java/com/clip/api/user/exception/NotFoundUserException.java
  onething/boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  onething/boot/api/src/main/java/com/clip/global/a
  onething/boot/api/src/main/java/com/clip/global/config/jwt/CustomClaims.java
  onething/boot/api/src/main/java/com/clip/global/config/jwt/JWTProperties.java
  onething/boot/api/src/main/java/com/clip/global/config/jwt/JwtAuthenticationFilter.java
  onething/boot/api/src/main/java/com/clip/global/config/jwt/TokenProvider.java
  onething/boot/api/src/main/java/com/clip/global/config/jwt/TokenType.java
  onething/boot/api/src/main/java/com/clip/global/config/jwt/exception/InvalidTokenException.java
  onething/boot/api/src/main/java/com/clip/global/config/jwt/exception/NotFoundTokenException.java
  onething/boot/api/src/main/java/com/clip/global/config/security/SecurityConfig.java
  onething/boot/api/src/main/java/com/clip/global/config/security/exclude/ExcludeAuthPathProperties.java
  onething/boot/api/src/main/java/com/clip/global/config/swagger/SwaggerConfig.java
  onething/boot/api/src/main/java/com/clip/global/exception/ValidExceptionHandler.java
  onething/boot/api/src/main/resources/application.yml
  onething/boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  onething/boot/api/src/test/java/boot/api/com/clip/global/config/jwt/TokenProviderTest.java
  onething/boot/api/src/test/java/com/clip/api/ApiApplicationTests.java
  onething/boot/api/src/test/java/data/coredata/com/clip/auth/entity/repository/TokenRepositoryTest.java
  onething/boot/api/src/test/java/data/coredata/com/clip/user/entity/repository/UserRepositoryTest.java
  onething/boot/api/src/test/resources/application.yml
  onething/boot/batch/src/test/java/com/clip/batch/BatchApplicationTests.java
  onething/data/core-data/build.gradle
  onething/data/core-data/src/main/java/com/clip/auth/entity/Token.java
  onething/data/core-data/src/main/java/com/clip/auth/repository/TokenRepository.java
  onething/data/core-data/src/main/java/com/clip/auth/service/TokenService.java
  onething/data/core-data/src/main/java/com/clip/user/entity/City.java
  onething/data/core-data/src/main/java/com/clip/user/entity/County.java
  onething/data/core-data/src/main/java/com/clip/user/entity/TermsAcceptance.java
  onething/data/core-data/src/main/java/com/clip/user/entity/User.java
  onething/data/core-data/src/main/java/com/clip/user/exception/NicknameAlreadyExistsException.java
  onething/data/core-data/src/main/java/com/clip/user/exception/PhoneNumberAlreadyExistsException.java
  onething/data/core-data/src/main/java/com/clip/user/repository/TermsAcceptanceRepository.java
  onething/data/core-data/src/main/java/com/clip/user/repository/UserRepository.java
  onething/data/core-data/src/main/java/com/clip/user/service/TermsAcceptanceService.java
  onething/data/core-data/src/main/java/com/clip/user/service/UserService.java
  onething/data/core-data/src/test/java/com/clip/coredata/CoreDataApplicationTests.java
  onething/data/office-data/src/main/resources/application.yml
  onething/data/office-data/src/test/java/com/clip/officedata/OfficeDataApplicationTests.java
Labels: feature

#4 Feat/signin signup dto add firebase token
  onething/boot/api/build.gradle
  onething/boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/LoginDto.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/SignupDto.java
  onething/boot/api/src/main/java/com/clip/api/user/mapper/TermsAcceptanceMapper.java
  onething/boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  onething/boot/api/src/test/java/data/coredata/com/clip/user/entity/repository/UserRepositoryTest.java
  onething/data/core-data/src/main/java/com/clip/user/entity/DeviceType.java
  onething/data/core-data/src/main/java/com/clip/user/entity/User.java
  onething/data/core-data/src/main/java/com/clip/user/repository/UserRepository.java
  onething/data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: feature

#6 번호로 유저 정보 조회하는 API 구현 및 테스트 작성
  onething/boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/UserInfoDto.java
  onething/boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  onething/boot/api/src/test/java/data/coredata/com/clip/user/entity/repository/UserRepositoryTest.java
  onething/data/core-data/src/main/java/com/clip/user/exception/UserNotFoundException.java
  onething/data/core-data/src/main/java/com/clip/user/repository/UserRepository.java
  onething/data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: feature

#8 온보딩 회원의 성별과 생일, 활동지역 업데이트 API 구현
  onething/boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateUserDetailInfoDto.java
  onething/boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  onething/boot/api/src/test/java/data/coredata/com/clip/user/entity/repository/UserRepositoryTest.java
  onething/data/core-data/src/main/java/com/clip/user/entity/City.java
  onething/data/core-data/src/main/java/com/clip/user/entity/County.java
  onething/data/core-data/src/main/java/com/clip/user/repository/UserRepository.java
  onething/data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: feature

#9 UserAccountService Test Case 추가
  onething/boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateUserDetailInfoDto.java
  onething/boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  onething/data/core-data/src/main/java/com/clip/auth/repository/TokenRepository.java
Labels: test

#22 사용 가능한 닉네임 확인 API 구현 및 테스트
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  boot/api/src/test/java/data/coredata/com/clip/user/entity/repository/UserRepositoryTest.java
  data/core-data/src/main/java/com/clip/user/repository/UserRepository.java
  data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: feature

#26 회원 프로필 기본 정보 조회 API 구현 및 테스트
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/RetrieveUserProfileInfo.java
  boot/api/src/main/java/com/clip/api/user/mapper/UserProfileMapper.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: feature, 정우

#28 FCM 토큰 업데이트 API, 알림 ON/OFF API
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/SignupDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateFCMDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateNotifyAllowDto.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  data/core-data/src/main/java/com/clip/user/entity/User.java
Labels: feature, 정우

#33 refactor/setter-remove
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  data/core-data/src/main/java/com/clip/user/entity/User.java
  data/core-data/src/main/resources/application-core-data.yml
Labels: 정우, refactor

#35 feat/user-info-modify
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  boot/api/src/main/java/com/clip/api/docs/user/UserInfoDocs.java
  boot/api/src/main/java/com/clip/api/user/controller/UserAccountController.java
  boot/api/src/main/java/com/clip/api/user/controller/UserInfoController.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/JobCategory.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/Language.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateDietaryDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateJobDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateLanguageDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/UpdateRelationshipDto.java
  boot/api/src/main/java/com/clip/api/user/mapper/JobMapper.java
  boot/api/src/main/java/com/clip/api/user/mapper/LanguageMapper.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  data/core-data/src/main/java/com/clip/user/entity/Job.java
  data/core-data/src/main/java/com/clip/user/entity/User.java
  data/core-data/src/main/java/com/clip/user/repository/JobRepository.java
Labels: feature, 정우

#37 feat/user-info-retrieve
  boot/api/src/main/java/com/clip/api/docs/user/UserInfoDocs.java
  boot/api/src/main/java/com/clip/api/user/controller/UserInfoController.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/DietaryDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/JobDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/LanguageDto.java
  boot/api/src/main/java/com/clip/api/user/controller/dto/RelationshipDto.java
  boot/api/src/main/java/com/clip/api/user/mapper/JobMapper.java
  boot/api/src/main/java/com/clip/api/user/mapper/LanguageMapper.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  data/core-data/src/main/java/com/clip/user/entity/User.java
Labels: feature, 정우

#39 feat/report
  boot/api/src/main/java/com/clip/api/docs/report/ReportDocs.java
  boot/api/src/main/java/com/clip/api/report/controller/ReportController.java
  boot/api/src/main/java/com/clip/api/report/controller/dto/ReportDto.java
  boot/api/src/main/java/com/clip/api/report/mapper/ReportMapper.java
  boot/api/src/main/java/com/clip/api/report/service/UserReportService.java
  boot/api/src/test/java/boot/api/com/clip/api/report/service/UserReportServiceTest.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  data/core-data/build.gradle
  data/core-data/src/main/java/com/clip/report/entity/Report.java
  data/core-data/src/main/java/com/clip/report/entity/ReportCategory.java
  data/core-data/src/main/java/com/clip/report/repository/ReportRepository.java
  data/core-data/src/main/java/com/clip/report/service/ReportService.java
Labels: feature, 정우

#42 토큰이 필요한 API를 호출 시 토큰이 누락되었으면 401을 반환하도록 변경
  boot/api/src/main/java/com/clip/api/docs/report/ReportDocs.java
  boot/api/src/main/java/com/clip/api/docs/user/UserAccountDocs.java
  boot/api/src/main/java/com/clip/api/docs/user/UserInfoDocs.java
  boot/api/src/main/java/com/clip/global/config/jwt/JwtAuthenticationFilter.java
Labels: 정우, refactor

#45 feat/payment-entity
  boot/api/src/test/java/data/coredata/com/clip/order/entity/repository/OneThingOrderRepositoryTest.java
  data/core-data/src/main/java/com/clip/matching/entity/OneThingMatching.java
  data/core-data/src/main/java/com/clip/matching/repository/OneThingMatchingRepository.java
  data/core-data/src/main/java/com/clip/order/entity/OneThingOrder.java
  data/core-data/src/main/java/com/clip/order/entity/OneThingOrderStatus.java
  data/core-data/src/main/java/com/clip/order/entity/RandomOrder.java
  data/core-data/src/main/java/com/clip/order/entity/RandomOrderStatus.java
  data/core-data/src/main/java/com/clip/order/repository/OneThingOrderRepository.java
  data/core-data/src/main/java/com/clip/order/repository/RandomOrderRepository.java
  data/core-data/src/main/java/com/clip/toss/entity/TossPayment.java
  data/core-data/src/main/java/com/clip/toss/entity/TossPaymentStatus.java
Labels: feature, 정우

#48 flyway init
  boot/api/src/main/resources/db/migration/V1__Init_table.sql
  data/core-data/src/main/resources/application-core-data.yml
Labels: feature, 정우

#58 fix/retrieve-user-phonenumber-info
  boot/api/src/main/java/com/clip/api/user/exception/NotFoundUserException.java
  boot/api/src/main/java/com/clip/api/user/service/UserAccountService.java
  boot/api/src/main/java/com/clip/global/config/swagger/SwaggerConfig.java
  boot/api/src/main/java/com/clip/global/exception/ValidExceptionHandler.java
  boot/api/src/test/java/boot/api/com/clip/api/user/service/UserAccountServiceTest.java
  data/core-data/src/main/java/com/clip/user/service/UserService.java
Labels: 정우

#40 Feat/backoffice auth
  boot/api/build.gradle
  boot/api/src/main/resources/application.yml
  boot/office/build.gradle
  boot/office/src/main/java/com/clip/global/config/SecurityConfig.java
  boot/office/src/main/java/com/clip/global/config/WebConfig.java
  boot/office/src/main/java/com/clip/global/security/CustomAuthenticationFailureHandler.java
  boot/office/src/main/java/com/clip/global/security/CustomAuthenticationSuccessHandler.java
  boot/office/src/main/java/com/clip/global/security/LoginAttemptFilter.java
  boot/office/src/main/java/com/clip/global/security/util/LoginAttemptManager.java
  boot/office/src/main/java/com/clip/office/admin/controller/AdminController.java
  boot/office/src/main/java/com/clip/office/admin/controller/dto/AdminLoginDto.java
  boot/office/src/main/java/com/clip/office/admin/service/AdminUserDetailsService.java
  boot/office/src/main/resources/application.yml
  boot/office/src/main/resources/static/css/style.css
  boot/office/src/main/resources/templates/fragments/content.html
  boot/office/src/main/resources/templates/fragments/header.html
  boot/office/src/main/resources/templates/index.html
  boot/office/src/main/resources/templates/layout/home.html
  boot/office/src/main/resources/templates/layout/layout.html
  data/core-data/src/main/java/com/clip/matching/entity/UserRandomMatching.java
  data/core-data/src/main/java/com/clip/user/entity/UserRole.java
  data/office-data/build.gradle
  data/office-data/src/main/java/com/clip/admin/entity/AdminUser.java
  data/office-data/src/main/java/com/clip/admin/exception/NotFoundAdminUserException.java
  data/office-data/src/main/java/com/clip/admin/repository/AdminUserRepository.java
  data/office-data/src/main/java/com/clip/admin/service/AdminUserService.java
  data/office-data/src/main/resources/application-office-data.yml
Labels: feature, 승범
